# Specify absolute paths to files/directories, and use /home/... instead of /panfs/...  For some reason, singularity is now having bind issues with use of latter.

outname: "AncInf" # MODIFY: prefix used for naming output
query: "PATH_TO_PLINK_PREFIX" #MODIFY: Prefix for PLINK files containing all of the query samples for ancestry inference
reference:
  vcf: "/home/araduski/araduski/misc/ALL.phase3_shapit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz" #MODIFY: Location of VCF with reference populations (e.g. 1000 Genomes VCF
  subpops: "accessory/1000G_PopLabels.txt" #MODIFY: File that labels each individual in the reference dataset with the population they are from.  Used as input into pop_map function in Snakefile
  genmap: "/home/araduski/araduski/misc/genetic_map_hg38.txt" #MODIFY: tab-separated file with 3 column per line: chromosome, physical base position, genetic map position.
  subset_bcf: 'none' #Not required. If the 'vcf' file had already been subset for the pops listed below (e.g. in a prior run), this can be provided here to avoid needing to repeat the step.
singularity:
  use_singularity: 'true' #Use a singularity image (i.e. set to true) if possible.  Pipeline has only been tested/debugged with singularity.
  image: '/home/araduski/shared/singularity/AncestryInference.sif' # MODIFY: Path to singularity image file.  The one I used for everything is named AncestryInference.sif, which can be created from scratch using .def file in AncInf repo.
  code: 'scripts/' #Path to the scripts directory that was cloned with repo.  Should not need to change this value.
  module: 'module load singularity' #Command that the HPC requires for use of singularity.  Set to empty string if singularity is loaded by default.
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. Must be in an acceptable format for subsetting plink files (One sample per line, two columns: fid iid)
rfmix:
  ref_pops: "YRI,GWD,ESN,MSL,LWK,CEU,FIN,IBS,TSI,PUR,CLM,PEL,MXL,CDX,CHB,CHS,JPT,KHV,BEB,GIH,ITU,PJL,STU" # Reference Populations to include.  Labels for each reference population is specified in pop_names
  pop_names: "AFR,AFR,AFR,AFR,AFR,EUR,EUR,EUR,EUR,AMR,AMR,AMR,AMR,EAS,EAS,EAS,EAS,EAS,SAS,SAS,SAS,SAS,SAS" # Desired names (i.e. superpopulation names) of reference populations.  MUST BE IN SAME ORDER AS ref_pops
  threads: "12" # Number of processors to use for parallel computation.  12 is good for array-sized datasets, but I've increased up to 48 for WGS or imputed data.
  generations: "8" #Generations since admixture began.  7 or 8 is often used for African-American admixture and 12 for Latinx admixture.  Appropriate value for when query data contains a mix of ancestries is an open question. Best approach would be to analyze separately.
  reanalyze_reference: "true" #In the case a set of reference haplotypes may not be of "pure" ancestry and may themselves be somewhat admixed, the option --reanalyze-reference will cause the program to analyze the reference haplotypes as if they were query haplotypes, in addition to analyzing the query input.
  window_size: "0.2"  # Specified in cM.  Default is 0.2 cM, which corresponds to ~100 - 150 kb windows.  If fewer than 10 SNPs are present in the window, then window is expanded.  For arrays, ~0.2 is likely the max resolution, but WGS data could handle 0.02
chroms: 'all'
bcftools:
  threads: '6' #6 is reasonable here
phase:
  threads: "12"
  pbwt_depth: "4" #Higher values may increase accuracy, but greatly increases runtimes.  4 is reasonable.
  sequence_data: 'false' #Set to true if source is WGS data.
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
python: 'python3.8' #python command for singularity to use.  Don't change.

dir:
  main: "/home/spectorl/pmonnaha/ancestry/" #CURRENTLY UNUSED
  scratch: "/scratch.global/pmonnaha/"
  out: "/scratch.global/pmonnaha/snakemake_testing/"
  code: './scripts/'

perform_QC: 'false' # This has not been thoroughly tested, so should be left as 'false'.  QC should be performed by external QC pipeline (e.g. DataPrep pipeline).
QC: #This section can be ignored since it is not used when 'perform_QC' is set to false.
  vm1: "0.2"
  gm: "0.1"
  vm2: "0.05"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "0.0000001"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.0000001"  # p-value treshold for test of whether missingness varies by sex
