# Specify absolute paths to files/directories, and use /home/... instead of /panfs/...  For some reason, singularity is now having bind issues with use of latter.

outname: "AncInf" # MODIFY: prefix used for naming output
query: "PATH_TO_PLINK_PREFIX" #MODIFY: Prefix for PLINK files containing all of the query samples for ancestry inference
reference:
  vcf: "PATH_TO_DATA_SUBDIRECTORY/ALL.phase3_shapit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz" #MODIFY: Location of VCF with reference populations
  subpops: "accessory/1000G_PopLabels.txt" #MODIFY
  genmap: "PATH_TO_DATA_SUBDIRECTORY/genetic_map_hg19.txt" #MODIFY
  phased_bcf: 'none'
singularity:
  use_singularity: 'true'
  image: 'DIRECTORY_CONTAINING/AncestryInference.sif' # MODIFY
  code: 'scripts/'
  module: 'module load singularity' # MODIFY
perform_QC: 'false'
QC:
  vm1: "0.2"
  gm: "0.1"
  vm2: "0.05"  # Ultimate call rate for variants after removing low-callrate samples
  maf: "0.01"  # mimimum Minor allele frequency
  hwe: "0.0000001"  # p-value threshold for whether site follows hardy-weinberg
  mbs: "0.0000001"  # p-value treshold for test of whether missingness varies by sex
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. Must be in an acceptable format for subsetting plink files (One sample per line, two columns: fid iid)
rfmix:
  ref_pops: "YRI,GWD,ESN,MSL,LWK,CEU,FIN,IBS,TSI,PUR,CLM,PEL,MXL,CDX,CHB,CHS,JPT,KHV,BEB,GIH,ITU,PJL,STU" # Reference Populations to include.  Labels for each reference population is specified in pop_names
  pop_names: "AFR,AFR,AFR,AFR,AFR,EUR,EUR,EUR,EUR,AMR,AMR,AMR,AMR,EAS,EAS,EAS,EAS,EAS,SAS,SAS,SAS,SAS,SAS" # Desired names (i.e. superpopulation names) of reference populations.  MUST BE IN SAME ORDER AS ref_pops
  threads: "12" # Number of processors to use for parallel computation
  generations: "8" #Generations since admixture began
  reanalyze_reference: "true" #In the case a set of reference haplotypes may not be of "pure" ancestry and may themselves be somewhat admixed, the option --reanalyze-reference will cause the program to analyze the reference haplotypes as if they were query haplotypes, in addition to analyzing the query input.
  window_size: "0.02"  # Specified in cM.  Default is 0.2 cM, which corresponds to ~100 - 150 kb windows
chroms: 'all'
bcftools:
  threads: '6'
phase:
  threads: "12"
  pbwt_depth: "4"
  sequence_data: 'false'
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
dir:
  main: "/home/spectorl/pmonnaha/ancestry/" #CURRENTLY UNUSED
  scratch: "/scratch.global/pmonnaha/"
  out: "/scratch.global/pmonnaha/snakemake_testing/"
  code: './scripts/'
